### PR TITLE
Added support for long arrays

### PR DESCRIPTION
**Pull request by sourcehunter**
For newer versions of Mincraft (I had to work with 1.12 and 1.13), some values are stored as Arrays of Long values, for example references to structures in chunks.

### CODE REVIEW

**Comment by sjmulder** [comment]
Thanks @sourcehunter! Code looks good at first sight. Hopefully I can get to giving it a try and a better look tonight, maybe adding a test too.

**Comment by sourcehunter** [comment]
Thanks for the fast reply. Totally forgot that. I will provide a test case.

**Comment by sourcehunter** [comment]
I found one inconsistency between nbt-js and NBTExplorer (https://github.com/jaquadro/NBTExplorer) where longs are stored in different int order. NBTExplorer stores the lower part of the long first and then the upper part, nbt-js does it the other way around. I'm not sure which one is correct, because I'm not that familiar with the file format.

**Comment by sjmulder** [comment]
Thanks! Re. the byte order, one would expect that to be specified somewhere. I'll have a look asap.

**Comment by sjmulder** [comment]
I think Substrate (the library NBTReader uses) is correct. I've opened the above linked issue to investigate.

This PR looks good, thanks for the excellent work.

**Pull request merged**
